### ISSUE TITLE
Heroku Deploy no worky

### ISSUE THREAD

**Issue by DarthHater** [salesforce/salesforce-cla#13]
Hello!

I'm trying to get this setup as I would find it super useful. However, when I deploy to Heroku and fill out the GH stuff, I keep getting:

```
2018-02-16T19:16:42.603799+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=sonatypeclatest.herokuapp.com request_id=f8bf9c55-f9ea-4819-b4b1-0da6ef2a07b0 fwd="24.237.89.76" dyno= connect= service= status=503 bytes= protocol=https
```

That error is fairly generic and hard to figure out, so I went ahead and logged in to bash to try and start the server myself:

```
~/target/universal/stage/bin $ ./salesforce-cla -Dhttp.port=$PORT
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] o.f.c.i.u.VersionPrinter - Flyway 4.2.0 by Boxfuse
[info] o.f.c.i.d.DbSupportFactory - Database: jdbc:postgresql://DATABASE(PostgreSQL 10.2)
Oops, cannot start the server.
@herokuID: Database 'default' needs migration!
	at org.flywaydb.play.PlayInitializer.$anonfun$checkState$1(PlayInitializer.scala:131)
	at org.flywaydb.play.PlayInitializer.$anonfun$checkState$1$adapted(PlayInitializer.scala:126)
	at scala.Option.foreach(Option.scala:257)
	at org.flywaydb.play.PlayInitializer.checkState(PlayInitializer.scala:126)
	at org.flywaydb.play.PlayInitializer.$anonfun$onStart$1(PlayInitializer.scala:149)
	at org.flywaydb.play.PlayInitializer.$anonfun$onStart$1$adapted(PlayInitializer.scala:145)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
	at org.flywaydb.play.PlayInitializer.onStart(PlayInitializer.scala:145)
	at org.flywaydb.play.PlayInitializer.<init>(PlayInitializer.scala:164)
	at org.flywaydb.play.PlayInitializer$$FastClassByGuice$$fd53e8fe.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

This is fairly puzzling, I'm kinda fumbling my way through this so any help would be appreciated! Stoked on the prospect of using this!

The error is generic enough to figure out (database appears to have no tables, etc...) just didn't expect this from deploying via Heroku. Perhaps some doc updates needed?

**Comment by DarthHater** [comment]
I was able to get past this by: `./salesforce-cla -Dhttp.port=$PORT -Ddb.default.migration.auto=true` from Heroku.

If you can describe how you'd like this handled I'll gladly contribute something back.

**Comment by jamesward** [comment]
Thanks for being the first to try this! :)  I'll see if there is a better way to handle this.

**Comment by DarthHater** [comment]
Not a problem.

As well, I tried to manually run the scripts myself and that caused a world of nightmares due to the constraints. Might want to make the migration script CASCADE deletes, etc... otherwise it'll barf on someone doing something like what I did.
